// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwpiolesrltbmipaaslq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3cGlvbGVzcmx0Ym1pcGFhc2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTY2MDAsImV4cCI6MjA2NTY3MjYwMH0.6oUhWC8Pg0nPwd3MNTvozOiaMp4ejM73L1_Z8za-3kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);